default:
  tags:
    - test-server
  image: yxliuramlab/cuda_jupyter_torch:102_191_0101

stages:
  - test


linting_test:
  stage: test
  script:
    - pip3 install flake8 mypy
    - mypy --install-types --non-interactive
    - flake8